apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
sepc:
  replicas: 1
  selector:
    matachLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
      - name: go-k8s
        image: jpedronascimentofilho/go-k8s
        ports:
          - containerPort: 8001
