apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>K8S</title>
      </head>
      <body>
        <h1>Code.education Rocks!</h1>
      </body>
    </html>
  
  # nginx.conf: |
  #   server {
  #     listen 80;
  #     index index.php index.html;
  #     root /usr/share/nginx/html;

  #   }